
server:
  port: 8081

spring:
  application:
    name: Amaze-Care

  datasource:
    url: jdbc:mysql://localhost:3306/amaze_care
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true
