spring:
  application:
    name: Amaze-Care

  datasource:
    url: jdbc:mysql://localhost:3306/amazecare
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  server:
    port: 8081

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
